### ISSUE TITLE
Add warning when HTTP blocks are in a project

### ISSUE THREAD

**Issue by Mrcomputer1** [SharpScratchMod/Sharp#10]
https://scratch.mit.edu/discuss/post/2030505/
https://scratch.mit.edu/discuss/post/2030562/
https://scratch.mit.edu/discuss/post/2031048/
https://scratch.mit.edu/discuss/post/2031060/

**Comment by NoMod-Programming** [comment]
The code for the username block warning is here: https://github.com/SharpScratchMod/Sharp/blob/master/src/ui/parts/StagePart.as
The code for checking for the username block is here: https://github.com/SharpScratchMod/Sharp/blob/master/src/blocks/BlockIO.as#L95
All that needs to be done is to modify it to check for http blocks as well.

**Comment by Mrcomputer1** [comment]
@NoMod-Programming Ok, I will do that later

**Comment by Mrcomputer1** [comment]
I think I have added the warning
