### ISSUE TITLE
Custom reporters freeze editor when the report block is not at end of define

### ISSUE THREAD

**Issue by Mrcomputer1** [SharpScratchMod/Sharp#15]
_Reported by: -io-_

If there is not "report" block at the end of a custom reporter define it will freeze the editor.
### Messages

@NoMod-Programming - Since you added the custom reporters you might know what to do.
@SharpScratchMod/developers - Maybe one of this team might know what to do as well

**Comment by scratchyone** [comment]
Hmm... I'll look into this if I have a chance.

**Comment by Mrcomputer1** [comment]
@scratchyone Ok

**Comment by CosmicWebServices** [comment]
bump

**Comment by ghost** [comment]
This issue hasn't been active for 4 months... 0.o

**Comment by Mrcomputer1** [comment]
@algmwc5 
Yeah, it is hard to fix. I have tried a few times but I never succeeded.
BTW I see you have changed your username

---

To try to get issue active again: @SharpScratchMod/developers

**Comment by NoMod-Programming** [comment]
Yup. To fix this, one would have to rewrite the interpreter (again), which would also fix a bunch of other issues with the custom reporters interpreter at the same time. Then, after rewriting the interpreter, one would have to get async reporters working while they call other scripts that report a value back to it (and if there is no `report ()` block, then use a default value. Rewriting the interpreter, sadly, is the easiest part of this. I'm currently stuck on getting async reporters to receive a value from another script.

**Comment by ghost** [comment]
Oh my

**Comment by Mrcomputer1** [comment]
I hope this fix works. It adds the report block if none is found.
Please tell me if it does not work.
