### ISSUE TITLE
Watcher for [LOCAL] variables includes sprite name AND [LOCAL]

### ISSUE THREAD

**Issue by NoMod-Programming** [SharpScratchMod/Sharp#16]
Can we have one or the other, please? My OCD is acting up on this 😜 . Also: You can rename a [LOCAL] variable to remove the work local, which can be confusing.

**Comment by ghost** [comment]
OK, I'll see what we can do

**Comment by Mrcomputer1** [comment]
I will try to fix this soon.

**Comment by CosmicWebServices** [comment]
bump

**Comment by ghost** [comment]
@CosmicWebServices excuse me?

**Comment by ghost** [comment]
Nevermind this issue is fixed
