### ISSUE TITLE
Moving custom reporters/booleans from sprite to sprite

### ISSUE THREAD

**Issue by Mrcomputer1** [SharpScratchMod/Sharp#19]
![sharpglitch1](https://cloud.githubusercontent.com/assets/5621168/19071987/2d928874-8a76-11e6-9dd3-bbe2368edf1b.gif)

When you move a reporter or boolean to another sprite the define hat will change from a hat to a reporter or boolean. It will still report but you can't attach any new blocks. If you disconnect any blocks you can't reattach them.

Note: The report block doesn't affect the glitch.

**Comment by ghost** [comment]
Hmm, can we get @NoMod-Programming here?

**Comment by Mrcomputer1** [comment]
@NoMod-Programming @SharpScratchMod/developers

**Comment by NoMod-Programming** [comment]
This would be the culprit: https://github.com/SharpScratchMod/Sharp/blob/master/src/blocks/Block.as#L579 Simply replace `procedureType ? procedureType : type` with `type`. I don't know why I wrote that line like I did, but that should fix it.

**Comment by ghost** [comment]
Ah, okay
Thanks :)

**Comment by ghost** [comment]
Has this been tested?

**Comment by Mrcomputer1** [comment]
@algmwc5 Yes

**Comment by ghost** [comment]
Okay

**Comment by Mrcomputer1** [comment]
Thanks @NoMod-Programming

The only problem with it is that custom reporter's outline of the block stops being an outline when moved to another sprite/to the stage. This does not seem to happen to normal custom blocks and booleans.

![sharpglitch2](https://cloud.githubusercontent.com/assets/5621168/19101154/e8811adc-8b08-11e6-8560-c191f3ca33ee.PNG)

I will create an issue for it (#20) but since it is very minor and doesn't affect the custom reporter it doesn't need to be fixed.
