### ISSUE TITLE
The @rabbit doesn't get hidden/removed when you edit a block with no screen refresh

### ISSUE THREAD

**Issue by ghost** [SharpScratchMod/Sharp#23]
I don't think this is supposed to happen 📦 

![rabbit](https://cloud.githubusercontent.com/assets/6393827/19869307/5ad0c6c4-9f71-11e6-8635-92a4c590e590.png)
After clicking OK, it adds another rabbit.

**Comment by Mrcomputer1** [comment]
_Note: I have not yet updated the online editor or offline editors. I will do this now. I will update this when done._
**Edit: See below**

**Comment by Mrcomputer1** [comment]
Done.

**Comment by ghost** [comment]
Timezone difference made this really quick to solve :P 

Thanks!
