### ISSUE TITLE
html error

### ISSUE THREAD

**Issue by LinuxRocks2000** [SharpScratchMod/Sharp#26]
i think you used the wrong html. instead of opening the swf via adobe flash, it just downloaded the swf. you should try making a new page and imbedding the swf.

**Comment by NoMod-Programming** [comment]
os+browser/version? On linux (at least Ubuntu+Firefox for me, at least), I needed to manually set swf files to have the adobe flash mimetype.

**Comment by Mrcomputer1** [comment]
You can try using https://sharpscratchmod.github.io/editor/ which embeds Sharp.swf. (I have also changed the link on the Sharp website to that one).

**Comment by LinuxRocks2000** [comment]
the link you sent worked, but the link on the site still doesn't. i have a problem with github where it doesn't update my site until i commit again or go through an entourage of boring reloads. is it working for you?

________________________________

**Comment by Mrcomputer1** [comment]
Oops. The reason the link on the site doesn't work is because I only updated the link on the download page. I have updated the rest of the links now.
