### ISSUE TITLE
Restore "hide"

### ISSUE THREAD

**Issue by ghost** [SharpScratchMod/Sharp#29]
Since Scratch 3.0 has been released, I'm using Sharp pretty much all the time when I'm making Scratch projects, and I upload them to Scratch when I'm finished. However, the "hide" block in Sharp doesn't exist, and instead there is a hide [sprite] block. The new feature is a **very good idea**, and I don't think that it should be removed. I think that the "hide" block should also be restored so that all uses of hiding are deleted in 3.0. Since I'm trying to make large projects with Sharp, it would take a VERY long time to find all the deletions of hide in 3.0, especially with the new obnoxious block size.
    I hope that this is considered!

**Comment by Mrcomputer1** [comment]
I have added a setting called "Restore Scratch show/hide Blocks". If you turn it on it will restore the Scratch show and hide blocks as "scratch show" and "scratch hide" under Sharp's "show [sprite]" and "hide [sprite]".

The setting can be enabled from the settings menu in File.

Note: If you load a Sharp or Scratch project with the show/hide block, they will appear red but will still work.

**Comment by ghost** [comment]
@Mrcomputer1 Thank you!

**Comment by ghost** [comment]
@Mrcomputer1 It isn't showing.

**Comment by Mrcomputer1** [comment]
@otsfan203 It works for me. Did it work before? If it did, could the setting have disabled itself somehow? If not, are you using the Sharp online editor, the Windows offline editor or macOS/Linux offline editor?

**Comment by ghost** [comment]
@Mrcomputer1 It worked before Sharp online editor.

**Comment by Mrcomputer1** [comment]
It still works for me. By "isn't showing" did you mean the show/hide blocks aren't showing in the looks category or that the show block isn't showing sprites. If it is the blocks that aren't showing, try turning the feature off and on in settings to see if that makes them appear. If it is the show block not working or if turning the show/hide blocks off and on didn't work, what browser do you use for Sharp?

**Comment by ghost** [comment]
@Mrcomputer1  It's not showing on the  array.

**Comment by Mrcomputer1** [comment]
@otsfan203 I'm not sure why it isn't working. It still is working for me and I haven't changed Sharp since adding this feature. Maybe try pressing "Reset Settings" in the settings menu (you will need to reload Sharp after that and re-enable the feature in settings after reloading). Also, what browser are you using to use Sharp?
