### ISSUE TITLE
Custom reporters/booleans

### ISSUE THREAD

**Issue by Mrcomputer1** [SharpScratchMod/Sharp#3]
# Important update!

We have decided to code the custom reporter/boolean system ourselves.
Please work on and see the new PR #11
### OLD:

We need help making custom reporters and booleans. Because I can't figure it out. :stuck_out_tongue: 

Problems:
- [-] Can't get the custom blocks to report anything
- [-] The reporter or boolean status is not saved to file

Working stuff:
- GUI options to set reporter/boolean status (could be improved) - commented out
- Setting type of block to reporter/boolean (but is not saved) - maybe commented out

**Comment by Mrcomputer1** [comment]
I have started copying the PR but did not finish if you want to help then see #4 
You will need repo access so comment here or on #4

OLD:

```
Got an idea - Don't work on this until I unassign myself or post
I am going to try to copy a PR from Scratch
```

**Comment by ghost** [comment]
Just so you know, there's a little bug (haven't debugged it) where call blocks in the palette suddenly switch to the weird rectangular stack blocks. Don't know when it happens though. A way of fixing it may be making different kinds of define blocks (with the same text of course). It would be like having 3 different more blocks categories.

Although I have no clue on how to implement it :stuck_out_tongue:

**Comment by Mrcomputer1** [comment]
:stuck_out_tongue: 
Once custom reporter/booleans are done it can be fixed then

**Comment by edward789121** [comment]
https://github.com/SharpScratchMod/Sharp/issues/6

**Comment by ghost** [comment]
Let's see if i'm able to help...

**Comment by Mrcomputer1** [comment]
# Important update!

We have decided to code the custom reporter/boolean system ourselves.
Please work on and see the new PR #11

**Comment by Mrcomputer1** [comment]
Complete thanks to NoMod-Programming
