### ISSUE TITLE
custom reporters/booleans

### ISSUE THREAD

**Issue by edward789121** [SharpScratchMod/Sharp#6]
instead of the confusing checkboxes, what if you could decide what it is itself?

**Comment by edward789121** [comment]
Like buttons you can click for a stack, reporter, or Boolean.

**Comment by Mrcomputer1** [comment]
We are working on copying an old PR from the scratch repo (which is hard because they have change parts of the code since that PR) This has buttons for the things instead of checkboxes. The existing checkboxes should disappear from the release build soon.

**Comment by edward789121** [comment]
Glad you understand.
